### ISSUE TITLE
Full regex

### ISSUE THREAD

**Issue by marcelinhov2** [lorey/socials-api#6]
It's possible to implement the "Monster regex" from the other repo into this one?

Thanks.

**Comment by lorey** [comment]
Hi Marcelo, I should. Have to update socials (it's implemented there). It's quite simple if you want to take a try. Otherwise you might have to wait a little. Thanks for your reminder anyway :+1:

**Comment by lorey** [comment]
I have created an issue in the other repo: https://github.com/lorey/socials/issues/9
